language: ruby
services:
- docker
- postgresql
- redis-server
rvm:
- 2.5
- 2.6
- 2.7
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install:
- docker pull redis
script:
- bundle exec rake db:postgresql:reset test:postgresql
