language: ruby

services:
- postgresql
- redis-server

rvm:
- 2.5
- 2.6
- 2.7
- 3.0
- ruby-head

gemfile:
- gemfiles/5.2.gemfile
- gemfiles/6.0.gemfile
- gemfiles/6.1.gemfile
- gemfiles/head.gemfile

matrix:
  allow_failures:
  - rvm: 3.0
    gemfile: gemfiles/5.2.gemfile
  - rvm: 3.0
    gemfile: gemfiles/6.0.gemfile
  - rvm: ruby-head

script:
- bundle exec rubocop
- bundle exec rake db:postgresql:reset test:postgresql

deploy:
  provider: rubygems
  api_key:
    secure: ZTq3W0zzbHsWP1QJQ0yf8NTqJP8tEm/vmMcRb+DL/Xs+EeZded4qI96Lh4RuL89oOf5/vAldVyq11I0ce3kz85cDHb6K/YzLlqks/4IJcsWnHKIEw6h6FWhLeuBt46TIWUZ8wBaqo2PUfoseJ0qs8ljXvZyoS0rAozLlMro5ktmDFH6Zaul+EURSoIeGT8fv8aeJMrOmLP0a3dSAD7TYSNNLfOrLHBjLUDnceiisihrAJUwbHaGy4BYU4jJFsci1o1mpuyXqZ3Kor3TtXqRLQryBt5KuB/VRcECFfMaiIkPzvQ6IlUo73RBimX1rdTyCutw8czrrc98ORkzeQ4uTBmG8bWX/HK6t2ZRvScGoCHesK4SBU2i0H0+NQ8JNe8e2n1xfo4mZ8aSGuHTjGqUoUQMywPGrKiIag5OQnctYZdtj9wmqwn3wEjDefZHJ9kP0pEle1Mj/NWTRsLHSFcBT2L4FHqTdHP8wQelAs59oHRTkDW7LQbtmYOxVyw68lu9DhD+mjFl5+BtC3Cv5hk8C2/QHq1OTKfV5k34cqFALBPjWG947q2GRu2cDgov/R/5UjJwSV5vW4AIZFjKaHAOaKk7jJx98G53qe4YFTxqEi6FRUaX0biF5xMhf0sEs1fRvIJxbFX0TgS7LCHYGrFqonvumkqOrDZyrd2h4FQe0vS4=
  gem: redis-memo
  on:
    tags: true
    repo: chanzuckerberg/redis-memo
    branch: main
  skip_cleanup: 'true'

env:
  global:
    secure: uc7k1Ug70potAcZt1tZ/I8QPukfYleBD7+mWqgJghs94nBlhBpGzD4nSaxPRToB7CYzmshYQOCKvUeMm2d9pR6Wd5UcTCC8RCQpR+XJU5mkhyL14uEzwzwbCTaJBHEx+w6J1x7OlQK7gXBrOUduD1DtfDz18wjt/dnDEJ1K78DDt1YFE7t6D0rs/FGX9CSHKj7fbon3YBZxQTfFPgAV+6ZZmtQ+cHpfv/Qztwu+RLqx5szG5hV/s2KgHfnwMnUWn13wrhfurFYpDiVGaXDOwuqT/JdEWX7Y3E9ZGnI89/xS25dqmhxZLJBryLy3lmMlH4nAtW4Tzg7o/IAKJAOPYyLtlXxHwsHI6meFf5hIYNCu3ZvT5bav652Is7MO5TIHtCx9lyvMUt8wUeC82L3tcLczRLzXFrAObbn3Q4G5BB9e7fj1hL9kq6z0gApIgIlMTqBpM4ilqDadRAw+a3Sk7YCi02Jufk6zJAsA1/sExCJJ9j3UrVN4mk6RG+Ea2GUXMEMeDNaCvAe89b12Bc6PmeOjoKET+IHLBtjG9JPeth8Ywa8p/O/HmCFJvYahN+6z8S5yA44QzKmcQw0q7kkGjweKV0Z8IcbfrJnBDaSsm0bJPLj2ah2xg9xods4MYNlGgaqOILCdXGjkewRyLUZAfPLUmyUcJ2k0Rs+Gs2TuvGlU=
