AllCops:
  ExtraDetails: true
  DisabledByDefault: true
  SuggestExtensions:
    rubocop-rake: false

inherit_from:
  - bundler.yml
  - gemspec.yml
  - layout.yml
  - lint.yml
  - metrics.yml
  - naming.yml
  - security.yml
  - style.yml
  - performance.yml
  - rspec.yml
